name: Build and test PRs

on:
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:
    uses: neoforged/actions/.github/workflows/build-prs.yml@main
    with:
      java: ${ jdkVersion in ['8', '11', '17'] ? jdkVersion : '17' }
      gradle_tasks: ${ project.tasks.findByName('test')?.enabled ? 'test' : 'build' }