name: Publish PRs to GitHub Packages

on:
  workflow_run:
    workflows: [Build and test PRs]
    types:
      - completed
  issue_comment:
    types:
      - edited
  pull_request_target:
    types:
      - opened

permissions:
  packages: write

jobs:
  publish-prs:
    if: ${ withPRPublishing ? 'true' : 'false # Option not enabled when the workflows were generated' }
    uses: neoforged/actions/.github/workflows/publish-prs.yml@main
    with:
      artifact_base_path: ${ commonGroup }
    secrets:
      PR_PUBLISHING_GH_APP_ID: \${{ secrets.PR_PUBLISHING_GH_APP_ID }}
      PR_PUBLISHING_GH_APP_KEY: \${{ secrets.PR_PUBLISHING_GH_APP_KEY }}
